# closed form ei moments 
function power(a,b)
    a^b
  end 
# current version which works well
function closed_ei_moments(t,init_conds, alpha, gamma, nu) 
  sqrt_term = sqrt(4*alpha*gamma + power(gamma - nu,2))
  exp_sqrt_term = exp(sqrt_term*t)
  exp_gamma = exp((gamma + nu) * t)
  if (abs(alpha - nu) > 1e-6)     
    # Mean E, then Mean I, then Var E, then Var I, then Cov EI
    moments = [init_conds[1] * ((4*alpha*(1 + exp_sqrt_term)*gamma + (gamma - nu)*((1 + exp_sqrt_term)*gamma - (-1 + exp_sqrt_term)*sqrt_term - (1 + exp_sqrt_term)*nu))/(2*exp(((gamma + sqrt_term + nu)*t)/2)*(4*alpha*gamma + power(gamma - nu,2)))) +
              init_conds[2] * ((alpha*(-1 + exp_sqrt_term))/(exp(((gamma + sqrt_term + nu)*t)/2)*sqrt_term)),# Mean I
              init_conds[1] * (((-1 + exp_sqrt_term)*gamma)/(exp(((gamma + sqrt_term + nu)*t)/2)*sqrt_term)) +
              init_conds[2] * ((4*alpha*(1 + exp_sqrt_term)*gamma + (gamma - nu)*((1 + exp_sqrt_term)*gamma + (-1 + exp_sqrt_term)*sqrt_term - (1 + exp_sqrt_term)*nu))/(2*exp(((gamma + sqrt_term + nu)*t)/2)*(4*alpha*gamma + power(gamma - nu,2)))),# Var E
              init_conds[1] * ((2*alpha*(gamma*nu + alpha*(-2*gamma + nu)))/(exp_gamma*(4*alpha*gamma + power(gamma - nu,2))*(alpha - nu)) - (gamma*(2*power(alpha,2)*(4*gamma + sqrt_term - nu) + (gamma + sqrt_term - nu)*(2*power(gamma,2) - 3*gamma*nu + power(nu,2)) + alpha*(9*power(gamma,2) + 5*gamma*sqrt_term - 8*gamma*nu - sqrt_term*nu + power(nu,2))))/(2*exp((gamma + sqrt_term + nu)*t)*(4*alpha*gamma + power(gamma - nu,2))*(3*alpha*gamma + power(gamma,2) + gamma*sqrt_term - gamma*nu + sqrt_term*nu + power(nu,2))) - (exp((-gamma + sqrt_term - nu)*t)*gamma*(-2*power(alpha,2)*(-4*gamma + sqrt_term + nu) - (-gamma + sqrt_term + nu)*(2*power(gamma,2) - 3*gamma*nu + power(nu,2)) + alpha*(9*power(gamma,2) - 5*gamma*sqrt_term - 8*gamma*nu + sqrt_term*nu + power(nu,2))))/(2*(4*alpha*gamma + power(gamma - nu,2))*(3*alpha*gamma + power(gamma,2) - gamma*sqrt_term - gamma*nu - sqrt_term*nu + power(nu,2))) + (2*power(alpha,2)*(4*gamma + sqrt_term - 3*nu) - (gamma - 2*nu)*(gamma + sqrt_term - nu)*nu + alpha*(power(gamma,2) + gamma*(sqrt_term - 9*nu) + 2*nu*(-sqrt_term + nu)))/(exp(((gamma + sqrt_term + nu)*t)/2)*(alpha - nu)*(12*alpha*gamma + 3*power(gamma,2) - gamma*sqrt_term - 6*gamma*nu - sqrt_term*nu + 3*power(nu,2))) + (exp(((-gamma + sqrt_term - nu)*t)/2)*((gamma - 2*nu)*nu*(-gamma + sqrt_term + nu) - 2*power(alpha,2)*(-4*gamma + sqrt_term + 3*nu) + alpha*(power(gamma,2) + 2*nu*(sqrt_term + nu) - gamma*(sqrt_term + 9*nu))))/((alpha - nu)*(12*alpha*gamma + 3*power(gamma,2) + gamma*sqrt_term - 6*gamma*nu + sqrt_term*nu + 3*power(nu,2)))) +
              init_conds[2] * ((alpha*(3*power(alpha,3)*(exp_gamma + 6*exp((gamma + sqrt_term + nu)*t) - 4*exp((3*(gamma + sqrt_term + nu)*t)/2) + exp((gamma + 2*sqrt_term + nu)*t) - 4*exp(((3*gamma + sqrt_term + 3*nu)*t)/2))*power(gamma,2) - (exp((3*(gamma + sqrt_term + nu)*t)/2) - exp(((3*gamma + sqrt_term + 3*nu)*t)/2))*gamma*sqrt_term*nu*(2*power(gamma,2) - 5*gamma*nu + 2*power(nu,2)) + power(alpha,2)*gamma*(2*exp((gamma + sqrt_term + nu)*t)*(2*power(gamma,2) - 5*gamma*nu - 7*power(nu,2)) + exp_gamma*(power(gamma,2) - gamma*(sqrt_term - 3*nu) + 2*nu*(-2*sqrt_term + nu)) + exp(((3*gamma + sqrt_term + 3*nu)*t)/2)*(-3*power(gamma,2) + 2*gamma*(-5*sqrt_term + nu) + 5*nu*(sqrt_term + nu)) + exp((3*(gamma + sqrt_term + nu)*t)/2)*(-3*power(gamma,2) + 5*nu*(-sqrt_term + nu) + 2*gamma*(5*sqrt_term + nu)) + exp((gamma + 2*sqrt_term + nu)*t)*(power(gamma,2) + 2*nu*(2*sqrt_term + nu) + gamma*(sqrt_term + 3*nu))) + alpha*(-(exp_gamma*gamma*(-gamma + sqrt_term)*(gamma - 2*nu)*nu) + exp((gamma + 2*sqrt_term + nu)*t)*gamma*(gamma + sqrt_term)*(gamma - 2*nu)*nu - 2*exp((gamma + sqrt_term + nu)*t)*power(nu,2)*(2*power(gamma,2) - 5*gamma*nu + 2*power(nu,2)) + exp((3*(gamma + sqrt_term + nu)*t)/2)*(power(gamma,3)*(2*sqrt_term - nu) + 5*gamma*(sqrt_term - nu)*power(nu,2) + 2*power(nu,3)*(-sqrt_term + nu) + power(gamma,2)*nu*(-15*sqrt_term + 4*nu)) + exp(((3*gamma + sqrt_term + 3*nu)*t)/2)*(-5*gamma*power(nu,2)*(sqrt_term + nu) + 2*power(nu,3)*(sqrt_term + nu) - power(gamma,3)*(2*sqrt_term + nu) + power(gamma,2)*nu*(15*sqrt_term + 4*nu)))))/(exp((2*gamma + sqrt_term + 2*nu)*t)*gamma*(9*alpha*gamma + 2*power(gamma,2) - 5*gamma*nu + 2*power(nu,2))*(4*power(alpha,2)*gamma - power(gamma - nu,2)*nu + alpha*(power(gamma,2) - 6*gamma*nu + power(nu,2))))) +
              init_conds[3] * ((2*alpha*power(1 + exp_sqrt_term,2)*gamma + (gamma - nu)*((1 + exp(2*sqrt_term*t))*gamma - (-1 + exp(2*sqrt_term*t))*sqrt_term - (1 + exp(2*sqrt_term*t))*nu))/(2*exp((gamma + sqrt_term + nu)*t)*(4*alpha*gamma + power(gamma - nu,2)))) +
              init_conds[4] * ((power(alpha,2)*power(-1 + exp_sqrt_term,2))/(exp((gamma + sqrt_term + nu)*t)*(4*alpha*gamma + power(gamma - nu,2)))) +
              init_conds[5] * ((alpha*(-1 + exp_sqrt_term)*(gamma - exp_sqrt_term*gamma + (1 + exp_sqrt_term)*sqrt_term + (-1 + exp_sqrt_term)*nu))/(exp((gamma + sqrt_term + nu)*t)*(4*alpha*gamma + power(gamma - nu,2)))),# Var I
              init_conds[1] * (-((gamma*(exp_gamma*(-1 + exp_sqrt_term)*(gamma - exp_sqrt_term*gamma + exp(((gamma + sqrt_term + nu)*t)/2)*sqrt_term)*nu*(2*power(gamma,2) - 5*gamma*nu + 2*power(nu,2)) + power(alpha,2)*gamma*(exp((3*(gamma + sqrt_term + nu)*t)/2)*(16*gamma - 3*sqrt_term - 8*nu) + exp(((3*gamma + sqrt_term + 3*nu)*t)/2)*(16*gamma + 3*sqrt_term - 8*nu) + exp_gamma*(2*gamma + 3*sqrt_term - nu) + 18*exp((gamma + sqrt_term + nu)*t)*(-2*gamma + nu) - exp((gamma + 2*sqrt_term + nu)*t)*(-2*gamma + 3*sqrt_term + nu)) + alpha*(exp_gamma*gamma*(2*gamma*sqrt_term - 11*gamma*nu - sqrt_term*nu + power(nu,2)) + exp((gamma + sqrt_term + nu)*t)*(-8*power(gamma,3) + 42*power(gamma,2)*nu - 18*gamma*power(nu,2) + 4*power(nu,3)) + 2*exp(((3*gamma + sqrt_term + 3*nu)*t)/2)*(2*power(gamma,3) + power(gamma,2)*(sqrt_term - 5*nu) - power(nu,3) + gamma*nu*(-5*sqrt_term + 4*nu)) - 2*exp((3*(gamma + sqrt_term + nu)*t)/2)*(-2*power(gamma,3) + power(nu,3) - gamma*nu*(5*sqrt_term + 4*nu) + power(gamma,2)*(sqrt_term + 5*nu)) - exp((gamma + 2*sqrt_term + nu)*t)*gamma*(-(nu*(sqrt_term + nu)) + gamma*(2*sqrt_term + 11*nu)))))/(exp((2*gamma + sqrt_term + 2*nu)*t)*(9*alpha*gamma + 2*power(gamma,2) - 5*gamma*nu + 2*power(nu,2))*(4*power(alpha,2)*gamma - power(gamma - nu,2)*nu + alpha*(power(gamma,2) - 6*gamma*nu + power(nu,2)))))) +
              init_conds[2] * ((-2*alpha*(alpha*gamma - power(nu,2)))/(exp_gamma*(4*alpha*gamma + power(gamma - nu,2))*(alpha - nu)) + (exp(((-gamma + sqrt_term - nu)*t)/2)*(-2*power(alpha,2)*gamma + (2*gamma - nu)*(gamma + sqrt_term - nu)*nu + alpha*(2*power(gamma,2) + 2*gamma*sqrt_term + 3*gamma*nu - sqrt_term*nu + power(nu,2))))/((-alpha + nu)*(12*alpha*gamma + 3*power(gamma,2) + gamma*sqrt_term - 6*gamma*nu + sqrt_term*nu + 3*power(nu,2))) + (-2*power(alpha,2)*gamma - (2*gamma - nu)*nu*(-gamma + sqrt_term + nu) + alpha*(2*power(gamma,2) - 2*gamma*sqrt_term + 3*gamma*nu + sqrt_term*nu + power(nu,2)))/(exp(((gamma + sqrt_term + nu)*t)/2)*(-alpha + nu)*(12*alpha*gamma + 3*power(gamma,2) - gamma*sqrt_term - 6*gamma*nu - sqrt_term*nu + 3*power(nu,2))) + (exp((-gamma + sqrt_term - nu)*t)*(2*power(alpha,2)*power(gamma,2) + (gamma + sqrt_term - nu)*nu*(power(gamma,2) - 3*gamma*nu + 2*power(nu,2)) + alpha*gamma*(power(gamma,2) + (sqrt_term - 5*nu)*nu + gamma*(sqrt_term + 2*nu))))/(2*(4*alpha*gamma + power(gamma - nu,2))*(3*alpha*gamma + power(gamma,2) - gamma*sqrt_term - gamma*nu - sqrt_term*nu + power(nu,2))) - (-2*power(alpha,2)*power(gamma,2) + nu*(-gamma + sqrt_term + nu)*(power(gamma,2) - 3*gamma*nu + 2*power(nu,2)) + alpha*gamma*(-power(gamma,2) + gamma*(sqrt_term - 2*nu) + nu*(sqrt_term + 5*nu)))/(2*exp((gamma + sqrt_term + nu)*t)*(4*alpha*gamma + power(gamma - nu,2))*(3*alpha*gamma + power(gamma,2) + gamma*sqrt_term - gamma*nu + sqrt_term*nu + power(nu,2)))) +
              init_conds[3] * ((power(-1 + exp_sqrt_term,2)*power(gamma,2))/(exp((gamma + sqrt_term + nu)*t)*(4*alpha*gamma + power(gamma - nu,2)))) +
              init_conds[4] * ((2*alpha*power(1 + exp_sqrt_term,2)*gamma + (gamma - nu)*((1 + exp(2*sqrt_term*t))*gamma + (-1 + exp(2*sqrt_term*t))*sqrt_term - (1 + exp(2*sqrt_term*t))*nu))/(2*exp((gamma + sqrt_term + nu)*t)*(4*alpha*gamma + power(gamma - nu,2)))) +
              init_conds[5] * (((-1 + exp_sqrt_term)*gamma*((-1 + exp_sqrt_term)*gamma + (1 + exp_sqrt_term)*sqrt_term + nu - exp_sqrt_term*nu))/(exp((gamma + sqrt_term + nu)*t)*(4*alpha*gamma + power(gamma - nu,2)))),# Cov EI
              init_conds[1] * ((12*power(alpha,3)*(exp_gamma - exp((3*(gamma + sqrt_term + nu)*t)/2) + exp((gamma + 2*sqrt_term + nu)*t) - exp(((3*gamma + sqrt_term + 3*nu)*t)/2))*power(gamma,2) + exp_gamma*(-1 + exp_sqrt_term)*gamma*nu*(gamma - exp_sqrt_term*gamma + (1 + exp_sqrt_term)*sqrt_term + (-1 + exp_sqrt_term)*nu)*(2*power(gamma,2) - 5*gamma*nu + 2*power(nu,2)) + alpha*(2*exp_gamma*gamma*(gamma + sqrt_term - nu)*(power(gamma,2) - 7*gamma*nu + power(nu,2)) - 2*exp((gamma + 2*sqrt_term + nu)*t)*gamma*(-gamma + sqrt_term + nu)*(power(gamma,2) - 7*gamma*nu + power(nu,2)) + exp((gamma + sqrt_term + nu)*t)*(-8*power(gamma,4) + 50*power(gamma,3)*nu - 60*power(gamma,2)*power(nu,2) + 22*gamma*power(nu,3) - 4*power(nu,4)) + exp(((3*gamma + sqrt_term + 3*nu)*t)/2)*(2*power(gamma,2) - 5*gamma*nu + 2*power(nu,2))*(power(gamma,2) + gamma*(sqrt_term - 2*nu) + nu*(sqrt_term + nu)) - exp((3*(gamma + sqrt_term + nu)*t)/2)*(2*power(gamma,2) - 5*gamma*nu + 2*power(nu,2))*(-power(gamma,2) + (sqrt_term - nu)*nu + gamma*(sqrt_term + 2*nu))) + power(alpha,2)*gamma*(-18*exp((gamma + sqrt_term + nu)*t)*(2*power(gamma,2) - 3*gamma*nu + power(nu,2)) + exp_gamma*(13*power(gamma,2) + gamma*(5*sqrt_term - 13*nu) + 4*nu*(-sqrt_term + nu)) + exp(((3*gamma + sqrt_term + 3*nu)*t)/2)*(5*power(gamma,2) + gamma*(5*sqrt_term - 14*nu) + 5*nu*(sqrt_term + nu)) + exp((gamma + 2*sqrt_term + nu)*t)*(13*power(gamma,2) + 4*nu*(sqrt_term + nu) - gamma*(5*sqrt_term + 13*nu)) + exp((3*(gamma + sqrt_term + nu)*t)/2)*(5*power(gamma,2) + 5*nu*(-sqrt_term + nu) - gamma*(5*sqrt_term + 14*nu))))/(2*exp((2*gamma + sqrt_term + 2*nu)*t)*(9*alpha*gamma + 2*power(gamma,2) - 5*gamma*nu + 2*power(nu,2))*(4*power(alpha,2)*gamma - power(gamma - nu,2)*nu + alpha*(power(gamma,2) - 6*gamma*nu + power(nu,2))))) +
              init_conds[2] * (-0.5*(alpha*(nu*(2*power(gamma,2) - 5*gamma*nu + 2*power(nu,2))*(-(exp((gamma + 2*sqrt_term + nu)*t)*gamma*(gamma + sqrt_term - nu)) + exp((3*(gamma + sqrt_term + nu)*t)/2)*(gamma - nu)*(gamma + sqrt_term - nu) + 2*exp((gamma + sqrt_term + nu)*t)*(gamma - nu)*nu + exp_gamma*gamma*(-gamma + sqrt_term + nu) - exp(((3*gamma + sqrt_term + 3*nu)*t)/2)*(gamma - nu)*(-gamma + sqrt_term + nu)) + power(alpha,2)*power(gamma,2)*(exp_gamma*(-7*gamma + 3*sqrt_term - 13*nu) - 18*exp((gamma + sqrt_term + nu)*t)*(gamma - nu) + 2*exp((3*(gamma + sqrt_term + nu)*t)/2)*(8*gamma + 3*sqrt_term + 2*nu) + exp(((3*gamma + sqrt_term + 3*nu)*t)/2)*(16*gamma - 6*sqrt_term + 4*nu) - exp((gamma + 2*sqrt_term + nu)*t)*(7*gamma + 3*sqrt_term + 13*nu)) + alpha*gamma*(-2*exp((gamma + sqrt_term + nu)*t)*(2*power(gamma,3) - 7*power(gamma,2)*nu - 2*gamma*power(nu,2) + 7*power(nu,3)) - 2*exp((gamma + 2*sqrt_term + nu)*t)*(power(gamma,3) + gamma*(3*sqrt_term - 8*nu)*nu + power(nu,2)*(-sqrt_term + nu) + power(gamma,2)*(sqrt_term + 4*nu)) + 2*exp_gamma*(-power(gamma,3) + power(gamma,2)*(sqrt_term - 4*nu) - power(nu,2)*(sqrt_term + nu) + gamma*nu*(3*sqrt_term + 8*nu)) + exp((3*(gamma + sqrt_term + nu)*t)/2)*(4*power(gamma,3) + power(gamma,2)*nu + gamma*(7*sqrt_term - 18*nu)*nu + power(nu,2)*(-5*sqrt_term + 9*nu)) + exp(((3*gamma + sqrt_term + 3*nu)*t)/2)*(4*power(gamma,3) + power(gamma,2)*nu + power(nu,2)*(5*sqrt_term + 9*nu) - gamma*nu*(7*sqrt_term + 18*nu)))))/(exp((2*gamma + sqrt_term + 2*nu)*t)*gamma*(9*alpha*gamma + 2*power(gamma,2) - 5*gamma*nu + 2*power(nu,2))*(4*power(alpha,2)*gamma - power(gamma - nu,2)*nu + alpha*(power(gamma,2) - 6*gamma*nu + power(nu,2))))) +
              init_conds[3] * (-0.5*((-1 + exp_sqrt_term)*gamma*((-1 + exp_sqrt_term)*gamma - (1 + exp_sqrt_term)*sqrt_term + nu - exp_sqrt_term*nu))/(exp((gamma + sqrt_term + nu)*t)*(4*alpha*gamma + power(gamma - nu,2)))) +
              init_conds[4] * ((alpha*(-1 + exp_sqrt_term)*((-1 + exp_sqrt_term)*gamma + (1 + exp_sqrt_term)*sqrt_term + nu - exp_sqrt_term*nu))/(2*exp((gamma + sqrt_term + nu)*t)*(4*alpha*gamma + power(gamma - nu,2)))) +
              init_conds[5] * ((((2*alpha*(1 + exp(2*sqrt_term*t))*gamma)/exp((gamma + sqrt_term + nu)*t) + power(gamma - nu,2)/exp_gamma)*(alpha - nu))/(4*power(alpha,2)*gamma - power(gamma - nu,2)*nu + alpha*(power(gamma,2) - 6*gamma*nu + power(nu,2))))]
  else 
    moments = [init_conds[1] * ((gamma/exp_gamma + nu)/(gamma + nu)) +
               init_conds[2] * ((nu - nu/exp_gamma)/(gamma + nu)), # Mean E
               init_conds[1] * ((gamma - gamma/exp_gamma)/(gamma + nu)) +
               init_conds[2] * ((gamma + nu/exp_gamma)/(gamma + nu)), # Mean I 
               init_conds[1] * ((gamma*((-1 + exp_gamma)*power(gamma,3) + exp_gamma*power(nu,3)*(3 + 2*nu*t + exp_gamma*(-3 + 2*nu*t)) - power(gamma,2)*nu*(2 - exp(2*(gamma + nu)*t) + exp_gamma*(-1 + 2*nu*t)) + gamma*power(nu,2)*(-2 - exp_gamma + exp(2*(gamma + nu)*t)*(3 + 2*nu*t))))/(exp(2*(gamma + nu)*t)*power(gamma + nu,4))) +
               init_conds[2] * ((nu*(power(gamma,3) + 2*power(nu,3) - power(nu,3)/exp(2*(gamma + nu)*t) + gamma*power(nu,2)*(-1 + 2*nu*t) + power(gamma,2)*nu*(3 + 2*nu*t) - (power(gamma,3) - gamma*power(nu,2) + power(gamma,2)*nu*(3 - 2*nu*t) + power(nu,3)*(1 + 2*nu*t))/exp_gamma))/power(gamma + nu,4)) +
               init_conds[3] * (power(gamma + exp_gamma*nu,2)/(exp(2*(gamma + nu)*t)*power(gamma + nu,2))) +
               init_conds[4] * ((power(-1 + exp(-((gamma + nu)*t)),2)*power(nu,2))/power(gamma + nu,2)) +
               init_conds[5] * ((2*(-1 + exp_gamma)*nu*(gamma + exp_gamma*nu))/(exp(2*(gamma + nu)*t)*power(gamma + nu,2))), # Var E
               init_conds[1] * ((gamma*(exp_gamma*(-1 + exp_gamma)*power(nu,3) + power(gamma,2)*nu*(-2 + 5*exp_gamma + exp(2*(gamma + nu)*t)*(-3 + 2*nu*t)) - gamma*power(nu,2)*(2 - 3*exp(2*(gamma + nu)*t) + exp_gamma*(1 + 2*nu*t)) + power(gamma,3)*(-1 + 2*exp(2*(gamma + nu)*t)*nu*t + exp_gamma*(1 + 2*nu*t))))/(exp(2*(gamma + nu)*t)*power(gamma + nu,4))) +
               init_conds[2] * ((nu*(-(power(nu,3)/exp(2*(gamma + nu)*t)) + gamma*(5*gamma*nu + power(nu,2) + 2*power(gamma,3)*t + power(gamma,2)*(-1 + 2*nu*t)) + (-5*power(gamma,2)*nu + power(nu,3) + power(gamma,3)*(1 - 2*nu*t) + gamma*power(nu,2)*(-1 + 2*nu*t))/exp_gamma))/power(gamma + nu,4)) +
               init_conds[3] * ((power(-1 + exp_gamma,2)*power(gamma,2))/(exp(2*(gamma + nu)*t)*power(gamma + nu,2))) +
               init_conds[4] * (power(gamma + nu/exp_gamma,2)/power(gamma + nu,2)) +
               init_conds[5] * ((2*(-1 + exp_gamma)*gamma*(exp_gamma*gamma + nu))/(exp(2*(gamma + nu)*t)*power(gamma + nu,2))), # Var I
               init_conds[1] * ((gamma*(-(exp_gamma*power(nu,4)*t) + power(gamma,2)*nu*(2 + 2*exp(2*(gamma + nu)*t)*nu*t + exp_gamma*(-2 + nu*t)) - power(gamma,3)*(-1 + exp_gamma*(1 + nu*t)) + gamma*power(nu,2)*(2 + exp_gamma*(3 + nu*t) + exp(2*(gamma + nu)*t)*(-5 + 2*nu*t))))/(exp(2*(gamma + nu)*t)*power(gamma + nu,4))) +
               init_conds[2] * ((power(nu,2)*(power(nu,2) + exp_gamma*(gamma - nu)*(3*gamma + nu + power(gamma,2)*t - power(nu,2)*t) + exp(2*(gamma + nu)*t)*gamma*(2*nu + 2*power(gamma,2)*t + gamma*(-3 + 2*nu*t))))/(exp(2*(gamma + nu)*t)*power(gamma + nu,4))) +
               init_conds[3] * (((-1 + exp_gamma)*gamma*(gamma + exp_gamma*nu))/(exp(2*(gamma + nu)*t)*power(gamma + nu,2))) +
               init_conds[4] * (-(((-1 + exp(-((gamma + nu)*t)))*nu*(gamma + nu/exp_gamma))/power(gamma + nu,2))) +
               init_conds[5] * ((exp_gamma*power(gamma - nu,2) + 2*gamma*nu + 2*exp(2*(gamma + nu)*t)*gamma*nu)/(exp(2*(gamma + nu)*t)*power(gamma + nu,2)))] # cov EI
  end 
    return(moments)
end 
  